<?php 
    
            echo  $this->url() ; 
?>
<div class="box">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">Editar Cadastro da Empresa</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
        
            <?php 
                if($this->success){
                    echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button></div>';
                }
                if($this->error){
                    echo '<div class="alert alert-error">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button></div>';
                }
                $form = $this->form ;
                $this->formElementErrors()
                        ->setMessageOpenFormat('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert"><i class="fa fa-times"></i></button>')
                        ->setMessageCloseString('</div>')
                        ->render($form);
                $form->setAttribute('class' , 'form-horizontal');
                $form->setAttribute('action' , $this->url('cadempresa/default' , array(
                                                                                    'controller' => 'cadempresa' , 
                                                                                    'action'     => 'editar' ,
                                                                                    'id'         => $this->id)));
                $form->prepare();
            ?>
           <?php echo $this->form()->openTag($form); ?>
           <?php echo $this->renderForm($form); ?>
           <?php echo $this->form()->closeTag($form); ?>

        
    </div>
    <!--*************** Fim Corpo da pagina***************-->
</div>