<div class="box">
    <div class="box-header with-border">
        <!--*************** Title da Pagina ***************-->
        <h3 class="box-title">Title</h3>
        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fa fa-minus"></i>
            </button>
        </div>
        <!--*************** Fim Title da Pagina ***************-->
    </div>
    <!--*************** Corpo da pagina ***************-->
    <div class="box-body">
    <?php
    /* @var $entity \Painel\Entity\Painel */
    if($this->success){
        echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">X</button></div>';
    }
    if($this->error){
        echo '<div class="alert alert-error">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">X</button></div>';
    }
    ?>

    <div class="table-responsive">
        <?php 
        if ($this->data): ?>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>
                            #
                        </th>
                        <th>
                            Logo
                        </th>
                        <th>
                            Icon Logo
                        </th>
                        <th>
                            Mensagem
                        </th>
                        <th style="width: 100px">
                            Ação
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($this->data as $entity) : ?>
                    <tr>
                        <td> <?php print_r($entity->getId()); ?>            </td>
                        <td> <?php echo $entity->getLogo(); ?>              </td>
                        <td> <?php echo $entity->getLogoIco(); ?>           </td>
                        <td> <?php echo $entity->getMimiDescrEmpre(); ?>    </td>
                        <td>
                            <a class="btn btn-success" href="<?php
                            echo $this->url('cadempresa/default',
                                    array(
                                        'controller' => 'cadempresa',
                                        'action'     => 'editar',
                                        'id'         => $entity->getId()));
                            ?>">
                                <i class="glyphicon glyphicon-edit"></i>
                            </a>
                            <a class="btn btn-danger" href="<?php
                            echo $this->url('cadempresa/default',
                                    array(
                                        'controller' => 'cadempresa',
                                        'action'     => 'excluir',
                                        'id'         => $entity->getId()));
                            ?>">
                                <i class="glyphicon glyphicon-remove"></i>
                            </a>
                        </td>
                    </tr>
            <?php endforeach; ?>
        <?php else: ?>
            <p>  Nenhum registro encontrado </p>
<?php endif; ?>
        </tbody>
    </table>
</div>
    </div>
    <!--*************** Fim Corpo da pagina***************-->
</div>