<?php

namespace Painel\Repository;

/**
 * PainelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PainelRepository extends \Doctrine\ORM\EntityRepository
{
}
