<?php
// module/Painel/view/painel/painel/add.phtml'

 $title = 'Cadastro da Empresa';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <div class="aler"
<h3>Adicionar Cliente</h3>
<?php 
$form = $this->form ;
$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">X</button>')
        ->setMessageCloseString('</div>')
        ->render($form);

$form->setAttribute('action' , $this->url('painel/default' , array(
                                                        'controller' => 'painel' , 
                                                        'action'     => 'inserir' )));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formCollection($form);?>
<?php echo $this->form()->closeTag($form);