<?php
/* @var $form \Zend\Form\Form */

$title = 'Cadastro da Empresa';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
if($this->success){
    echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">X</button></div>';
}
if($this->error){
    echo '<div class="alert alert-error">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">X</button></div>';
}

$form = $this->form ;
$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-error"><button type="button" class="close" data-dismiss="alert">X</button>')
        ->setMessageCloseString('</div>')
        ->render($form);

$form->setAttribute('action' , $this->url('painel/default' , array(
                                                        'controller' => 'painel' , 
                                                        'action'     => 'inserir' )));
$form->prepare();
?>

<?php echo $this->form()->openTag($form);?>
<?php echo $this->formCollection($form);?>
<?php echo $this->form()->closeTag($form);