<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon',
                    'type' => 'image/vnd.microsoft.icon',
                    'href' => $this->basePath() . '/imagem/php_logo.ico'))
                ->prependStylesheet($this->basePath() . 'css/site/vendor/plugins.css')
                ->prependStylesheet($this->basePath() . 'css/site/vendor/owl-carousel/owl.theme.css')
                ->prependStylesheet($this->basePath() . 'css/site/vendor/owl-carousel/owl.carousel.css')
                ->prependStylesheet($this->basePath() . 'css/site/vendor/fortawesome/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . 'css/site/default.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                
                ->prependFile($this->basePath() . '/js/site/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/site/js/jquery.js')
        ?>

    </head>
    <body>
        <header><!-- Inicio da Header -->
            <div class="container" id="container"> <!--Inicio do Container -->
                <div id="topo"><!--Inicio da Div Topo -->
                    <div id="logo">
                        <img src="imagem/php_logo.png" class="img-responsive" alt="" />
                    </div>
                    <div id="pesquisa"><!--Inicio da Div pesquisa  -->
                        <p>Olá, Seja bem-Vindo <a href=""> Faça Login </a> ou <a href=""> Cadastre-se</a>. </p>
                        <form action="">
                            <div class="input-group">
                                <input type="text" name="buscar" class="form-control" id="buscar" required placeholder="Pesquisar no Site... " />
                                <span class="input-group-btn">
                                    <button class="btn btn-info btn-lg" type="submit">
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                </span> 
                            </div> <!--Fim Input de Psequisa-->
                        </form> <!--Fim Formulario de Pesquisa Topo -->
                    </div> <!--Fim pesquisa -->
                </div> <!--Fim Topo -->
            </div> <!--Fim Container -->
        </header><!-- Fim da Header -->
        <div id="menu_navegacao"><!-- Inicio div menu -->
            <div class="container"><!-- Inicio da container -->
                <nav class="navbar navbar-default" id="menu_content"><!-- Inicio da taf Nav -->
                    <div class="container-fluid">
                        <!-- Brand and toggle get grouped for better mobile display -->
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <!-- Collect the nav links, forms, and other content for toggling -->
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <ul class="nav navbar-nav">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Menu Categoria <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Action</a></li>
                                        <li><a href="#">Another action</a></li>
                                        <li><a href="#">Something else here</a></li>
                                        <li role="separator" class="divider" > </li>
                                        <li><a href="#">Separated link</a></li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="#">One more separated link</a></li>
                                    </ul>
                                </li>
                                <li class="active"><a href="#">Início<span class="sr-only">(current)</span></a></li>
                                <li><a href="#">Empresa</a></li>
                                <li><a href="#">Contatos</a></li>
                                <li><a href="#">Serviços</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </div><!-- /.container-fluid -->
                </nav><!-- Fim tag nav -->
            </div><!-- Fim do container -->
        </div><!-- Fim da div menu -->


        <footer>
            <div class="container">
                <div class="content" id="footer-sidebar">
                    <div class="footer-widget footer-widget--about">
                        <a href="#" title="Criando sites profissionais passo a passo">
                            <img src="imagem/php_logo.png" class="img-responsive" alt="Criando sites profissionais passo a passo" title="Criando sites profissionais passo a passo">
                        </a>
                        <p>
                            Lorem ipsum ex vix illud nonummy, novum tation et his. At vix scriptaset patrioque scribentur, at pro fugit erts verterem molestiae, sed et vivendo ali Lorem ipsum ex vix illud nonummy, novum tation et his. At vix scripta patrioque scribentur...
                        </p>
                    </div>
                    <div class="footer-widget">
                        <h4 class="widget__title">
                            <span></span> Noticias
                        </h4>
                        <ul class="clearfix" id="fotos">
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                            <li>
                                <a href="#" title="Fotos do rodapé">
                                    <img src="images/card01.jpg" class="img-responsive" alt="Fotos do rodapé" title="Fotos do rodapé">
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div class="footer-widget">
                        <h4 class="widget__title">
                            <span></span> Localização
                        </h4>
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3658.307953558354!2d-46.189562099999975!3d-23.521423799999987!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94cdd83dfd10bbd9%3A0x7a904a3e6d7b06e9!2sR.+Bar%C3%A3o+de+Jacegua%C3%AD+-+Centro%2C+Mogi+das+Cruzes+-+SP!5e0!3m2!1spt-BR!2sbr!4v1440075997935" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
                    </div>
                </div>
            </div>
            <div id="redes-sociais">
                <div class="container">
                    <div class="content">
                        <div id="redes-sociais__container">
                            <ul id="redes-sociais__icons">
                                <li>
                                    <a href="#" class="icon icon--facebook" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--twitter" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--youtube" title=""></a>
                                </li>
                                <li>
                                    <a href="#" class="icon icon--gplus" title=""></a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    </body>
</html>
